[tool.black]
line-length = 90
target-version = ['py38']
skip-string-normalization = true
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \__pycache__
    | \.tox
    | \.venv
    | venv
    | buck-out
    | build
    | dist
    | alembic
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.isort]
line_length = 90
skip = 'alembic/,venv/,.venv/'
known_first_party = 'app'
known_third_party = 'fastapi, pydantic, sqlalchemy'
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true