"""add otp created time column

Revision ID: 0f7e921cbc13
Revises: 5ce477cd7ee3
Create Date: 2020-05-13 13:01:34.065163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7e921cbc13'
down_revision = '5ce477cd7ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('otp_created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('otp_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_created_at')
    op.drop_column('owner', 'otp_created_at')
    # ### end Alembic commands ###
