"""immutable address

Revision ID: 30c3d93498d1
Revises: db26174ec486
Create Date: 2020-06-12 18:19:30.659186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c3d93498d1'
down_revision = 'db26174ec486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('address', sa.Column('archived', sa.Boolean(), nullable=True))
    op.add_column('address', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # op.drop_index('idx_address_location', table_name='address')
    # op.drop_index('idx_shops_location', table_name='shops')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_shops_location', 'shops', ['location'], unique=False)
    op.create_index('idx_address_location', 'address', ['location'], unique=False)
    op.drop_column('address', 'deleted_at')
    op.drop_column('address', 'archived')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
