"""update owner table

Revision ID: 54f029830204
Revises: c96049c7b9a7
Create Date: 2020-05-10 23:24:45.274786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f029830204'
down_revision = 'c96049c7b9a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('owner', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('owner', sa.Column('name', sa.String(length=30), nullable=True))
    op.drop_index('ix_owner_username', table_name='owner')
    op.drop_column('owner', 'first_name')
    op.drop_column('owner', 'last_name')
    op.drop_column('owner', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('owner', sa.Column('last_name', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.add_column('owner', sa.Column('first_name', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.create_index('ix_owner_username', 'owner', ['username'], unique=True)
    op.drop_column('owner', 'name')
    op.drop_column('owner', 'last_seen')
    op.drop_column('owner', 'email_verified')
    # ### end Alembic commands ###
