"""add owner table

Revision ID: 76082d06c7a7
Revises: 89255db472dd
Create Date: 2019-11-11 11:51:25.156090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76082d06c7a7'
down_revision = '89255db472dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=25), nullable=True),
    sa.Column('last_name', sa.String(length=25), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('avatar_image', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_email'), 'owner', ['email'], unique=True)
    op.create_index(op.f('ix_owner_id'), 'owner', ['id'], unique=False)
    op.create_index(op.f('ix_owner_username'), 'owner', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_owner_username'), table_name='owner')
    op.drop_index(op.f('ix_owner_id'), table_name='owner')
    op.drop_index(op.f('ix_owner_email'), table_name='owner')
    op.drop_table('owner')
    # ### end Alembic commands ###
