"""orders and ordered_items tables

Revision ID: b6fb9692f762
Revises: d54778171038
Create Date: 2020-05-28 21:42:59.062942

"""
import sqlalchemy as sa

import sqlalchemy_utils
from alembic import op
from app.choices.order_status import ORDER_STATUS_TYPES

# revision identifiers, used by Alembic.
revision = 'b6fb9692f762'
down_revision = 'd54778171038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_datetime', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('shop_id', sa.Integer(), nullable=False),
        sa.Column('user_instructions', sa.String(length=150), nullable=True),
        sa.Column(
            'status',
            sqlalchemy_utils.types.choice.ChoiceType(
                ORDER_STATUS_TYPES, impl=sa.String(length=20)
            ),
            nullable=False,
        ),
        sa.Column('total_cost', sa.Numeric(scale=2), nullable=True),
        sa.ForeignKeyConstraint(['shop_id'], ['shops.id'],),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'],),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table(
        'ordered_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('cost', sa.Numeric(scale=2), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['items.id'],),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'],),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_ordered_items_id'), 'ordered_items', ['id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    # op.drop_index('idx_shops_location', table_name='shops')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_shops_location', 'shops', ['location'], unique=False)
    op.create_table(
        'spatial_ref_sys',
        sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            'auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
        sa.Column(
            'proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            '(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'
        ),
        sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey'),
    )
    op.drop_index(op.f('ix_ordered_items_id'), table_name='ordered_items')
    op.drop_table('ordered_items')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
