"""update user table

Revision ID: c96049c7b9a7
Revises: 76082d06c7a7
Create Date: 2020-05-10 20:19:12.087448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96049c7b9a7'
down_revision = '76082d06c7a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=30), nullable=True))
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'state')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'username')
    op.drop_column('user', 'bio')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'city')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('city', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('bio', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('state', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_column('user', 'name')
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
