"""add items table

Revision ID: d54778171038
Revises: d531f09700c4
Create Date: 2020-05-21 14:10:16.854703

"""
from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils
from app.choices.cost_unit import COST_UNIT_TYPES


# revision identifiers, used by Alembic.
revision = 'd54778171038'
down_revision = 'd531f09700c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('cost', sa.Numeric(scale=2), nullable=False),
    sa.Column('cost_unit', sqlalchemy_utils.types.choice.ChoiceType(COST_UNIT_TYPES), nullable=False),
    sa.Column('category', sa.String(length=25), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=True),
    sa.Column('item_available', sa.Boolean(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    # op.drop_index('idx_shops_location', table_name='shops')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_shops_location', 'shops', ['location'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
