"""cart table

Revision ID: ea97318f0bc6
Revises: daf1eaa11951
Create Date: 2021-06-03 23:37:29.323979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea97318f0bc6'
down_revision = 'daf1eaa11951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Extension for supporing exclude constraint
    op.execute("CREATE EXTENSION btree_gist")

    op.create_table('cart',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('item_quantity', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    postgresql.ExcludeConstraint((sa.column('user_id'), '='), (sa.column('shop_id'), '<>'), using='gist'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'user_id', name='_item_user_uc')
    )
    op.create_index(op.f('ix_cart_id'), 'cart', ['id'], unique=False)
    op.create_index(op.f('ix_cart_item_id'), 'cart', ['item_id'], unique=False)
    op.create_index(op.f('ix_cart_user_id'), 'cart', ['user_id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    # op.drop_index('idx_address_location', table_name='address')
    # op.drop_index('idx_shops_location', table_name='shops')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('idx_shops_location', 'shops', ['location'], unique=False)
    # op.create_index('idx_address_location', 'address', ['location'], unique=False)
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.drop_index(op.f('ix_cart_user_id'), table_name='cart')
    op.drop_index(op.f('ix_cart_item_id'), table_name='cart')
    op.drop_index(op.f('ix_cart_id'), table_name='cart')
    op.drop_table('cart')

    op.execute("DROP EXTENSION IF EXISTS btree_gist")

    # ### end Alembic commands ###
