"""new fields in user model

Revision ID: 34a52e4c3fda
Revises: aaefff0ffe81
Create Date: 2019-09-15 23:53:02.151540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a52e4c3fda'
down_revision = 'aaefff0ffe81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_image', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('bio', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(length=15), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'state')
    op.drop_column('user', 'city')
    op.drop_column('user', 'role')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'bio')
    op.drop_column('user', 'avatar_image')
    # ### end Alembic commands ###
